package com.jiang.android.translatetoast.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.jiang.android.translatetoast.db.model.Translate;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig translateDaoConfig;

    private final TranslateDao translateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        translateDaoConfig = daoConfigMap.get(TranslateDao.class).clone();
        translateDaoConfig.initIdentityScope(type);

        translateDao = new TranslateDao(translateDaoConfig, this);

        registerDao(Translate.class, translateDao);
    }
    
    public void clear() {
        translateDaoConfig.getIdentityScope().clear();
    }

    public TranslateDao getTranslateDao() {
        return translateDao;
    }

}
