package com.jiang.android.translatetoast.db.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TRANSLATE".
 */
public class Translate {

    private Long id;
    private String search_name;
    private String search_result;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Translate() {
    }

    public Translate(Long id) {
        this.id = id;
    }

    public Translate(Long id, String search_name, String search_result) {
        this.id = id;
        this.search_name = search_name;
        this.search_result = search_result;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSearch_name() {
        return search_name;
    }

    public void setSearch_name(String search_name) {
        this.search_name = search_name;
    }

    public String getSearch_result() {
        return search_result;
    }

    public void setSearch_result(String search_result) {
        this.search_result = search_result;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
